# Generated by Django 4.0.4 on 2022-04-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
