# Generated by Django 4.0.4 on 2022-04-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_inquiry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email_address',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
