# Generated by Django 4.0.4 on 2022-04-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_inquiry_email_address_alter_inquiry_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='phone_number',
        ),
    ]
